insert into clients (name) values ('Spinka, Parisian and Koch');
insert into clients (name) values ('Johns, Bechtelar and Gutmann');
insert into clients (name) values ('Frami-Stracke');
insert into clients (name) values ('Murray LLC');
insert into clients (name) values ('Kohler-McClure');
insert into clients (name) values ('Parisian LLC');
insert into clients (name) values ('Wilderman Group');
insert into clients (name) values ('Hayes-Kub');
insert into clients (name) values ('Oberbrunner LLC');
insert into clients (name) values ('Hudson-Ortiz');
insert into clients (name) values ('Miller and Sons');
insert into clients (name) values ('Collier Inc');
insert into clients (name) values ('Schuster-McDermott');
insert into clients (name) values ('Turcotte-Towne');
insert into clients (name) values ('Steuber-Stoltenberg');
insert into clients (name) values ('Carter, Harber and Botsford');
insert into clients (name) values ('Hilll, O''Kon and Batz');
insert into clients (name) values ('Gutkowski Group');
insert into clients (name) values ('Haag, Welch and Collins');
insert into clients (name) values ('Marquardt, Bogisich and Kilback');
